### ISSUE TITLE
Contoso-Site-Tracking.zip

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#1]
# Module: 00
#### Step: 00

Description of issue
The zip file Delete Contoso-Site-Tracking.zip was deleted. Do we still have a file and is it to be included. Which is out of date, slides or walkthroughs.
Regards Davide De Vita

@stephyang78
stephyang78 committed on Dec 19, 2019

Repro steps:

1.
1.
1.

**Comment by skulthm-ms** [comment]
I recovered the file.
