### ISSUE TITLE
Lab 4 Error

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#106]
# Lab 4 - Automated Solution
## Task: 3: Create a step to send an email to the visitor

The task name should be "Create a step to send an email to the expense requestor" instead of "visitor."

### Step: 9

The instructions have the student create a new expense report.  The problem is the field called "Report Total Amount."   You cannot set this to a value because this is a Rollup field based on another table...so you cannot edit the amount directly!

Side Note:   My Opinion:    Since the Model-Driven app adds the Contact table to the app,  and since this solution already includes the "Expense Report" table, then the lab should either already have a 1:Many relationship to the Contract table, or add instructions so the student creates the relationship.  Then in the Model-Driven app add the "Contact" as the Requestor, not use the "Owner" field from the User table...   Then have the Automated flow send the email to the Contact, not the User.  It just makes more sense to me.

**Comment by CeleneA** [comment]
Apologies for the delay - but the issues you raised have been fixed.
