### ISSUE TITLE
Mismatch between this version of the scenario, the diagram, and the follow on labs.

### ISSUE THREAD

**Issue by richbrooks** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#109]
# Module: 01
#### Step: Paragraph

I appreciate the move from Visits to Expenses.   But, the rest of the labs are not complete with the transition.   The image for the scenario is now mismatched and the PNG Markdown link is broken.  The last update was approximately 3 months ago.  What is the plan to complete the migration from Visits to Expenses.

Repro steps:

1. Read the updated scenario
2. Look at the image reference for the diagram
3. Realize there is a disconnect between the newly updated scenario and the images and steps on follow on labs.

**Comment by CeleneA** [comment]
I will address today

**Comment by Derekp20** [comment]
I notice that these discrepancies were mentioned in previous Issues that were closed, even though it was not fully fixed. Please don't close the issue until it is fixed, so that other trainers are aware of the problems.

**Comment by CeleneA** [comment]
@richbrooks @Derekp20 -
can you please let me know which discrepancies you are seeing? It is true that there are 2 different Bellows College scenarios for the PL-900 labs, as follows:
Data model: expenses
canvas app: expenses
model-driven app: expenses
bonus lab (copilot): visits
Power Automate: expenses
Power BI: visits
are there discrepancies within the labs? If yes, could you point those out? Absolutely want to get that fixed.
Thank you,
Celene

**Comment by Derekp20** [comment]
Lab 0 says "you will create a practice environment " . If you are using a lab provider it is provided, if you are using your own tenant, you need to create one, but no instructions on the type or how to create. This is only a Fundamentals course so it needs to be easy to follow. If you use your own Tenant, you need to add the "My Expenses App" sample to get the Expense Report table.

Lab 1. The Campus Management.png is not relevant in the new scenario.
Lab 1. You create a table called _Expense_, but do not use this table again.

Lab 2. Uses _Expense Report_ table. The Canvas App created only has 2 fields. There is no data in the table. We entered data into the Expense table, so searching for _Trip_ does not return any results. Should we have loaded the data? Need to add additional columns to the canvas to make it usable.

Lots of files in Allfiles folder that are no longer used.

I am testing using GoDeploy Labs. Also tried with my own Tenant.

**Comment by CeleneA** [comment]
Thank you for the details. I will work with go deploy to fix issues. You should not have to do any setup.

**Comment by schtoni1** [comment]
Lab01: 
The CampusManagement.png is from a different scenario (former Pl-100 Campus visits) and has nothing to do with the expenses scenario in this Lab! 


> T_o prepare your learning environments you will:
> 
> Refer to the **[data model document](https://github.com/MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals/blob/master/Allfiles/Campus Management.png)** for the metadata description (tables and relationships). You can hold ctrl + left-click or right-click the link to open the data model document in a new window._
