### ISSUE TITLE
Image bellow Step 17

### ISSUE THREAD

**Issue by richbrooks** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#110]
# Module: 03
#### Step:  Image on Step 16

Description of issue
- The image is reflecting the Visits from the prior PL-900.   

Repro steps:

1.  Accomplish the CoPilot Steps for the new Expenses
2.  Look at the image on Step 17
3.  Disconnect between the Expenses Screen that was created with Copilot and  the image of the Visits App.

**Comment by CeleneA** [comment]
I will address today

**Comment by CeleneA** [comment]
the lab is consistently and correctly based on a visit tracking scenario. Screenshot matches the scenario and lab steps.
