### ISSUE TITLE
No Expense Report Table is created

### ISSUE THREAD

**Issue by gethynellis** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#111]
# Module: 01
## Lab/Demo: 01 - No Expense Report Table is created

Description of issue

The Expense Report table does not exist. In the Dataverse data model lab 01. In the Lab the students create a table called Expenses - a basic table with six columns. The rest of the labs refer to a table called Expense Reports which doesn't exist because it doesn't get created but it is referencing different columns that are not in the expense table - so it looks like the steps are missing for the Expense Report Table

This has a knock-on effect on the remaining Labs

**Comment by Derekp20** [comment]
AS with issue #112, it may be related the Lab Environment not being correctly created. After GoDeploy recreated my labs, the Expense Reports table was present, but as mentioned above, it is not the table used in the the first lab. Also the data entered does not have the word "Trip" in it. The instructions for the previous lab should be changed for the table name, and to provide an item description that can then be search for in this lab. The 2 labs will then match up.

**Comment by CeleneA** [comment]
no repro
