### ISSUE TITLE
The sync options in the first lab don't exist

### ISSUE THREAD

**Issue by gethynellis** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#112]
# Module: 01
#### Step: 01

Description of issue - The sync option Expense type does not exist.

Repro steps:
### Create Expense Type Column
Select + New column.

Enter Expense Type for Display name.

Select Choice for Data type.

In Required, select Optional.

Set Sync with global Choice to Yes (recommended)

In Sync this choice with field, select Expense Type.

Set the Default choice field to None.

**Comment by Derekp20** [comment]
I experienced this same issue last week. The lab provider (GoDeploy) deleted my tenant, and when I restarted the lab the Global CHoise options were present. I should say that also the Dev One Environement had not been fully created, and was still showing as "Preparing".

**Comment by CeleneA** [comment]
cannot repro
