### ISSUE TITLE
No data for Lab 2

### ISSUE THREAD

**Issue by jamarx2** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#113]
# Labs: 2 How to build a canvas app
### Step 5: Once the Trip to Power Platform Conference record is displayed, select a row to navigate and open the Details screen for that Expense.

The Expense Report table referenced contains no data. When users get to the point of searching for the **Trip to the Power platform Conference**, there is nothing there. The table is empty.

**Comment by Derekp20** [comment]
This is a problem I experienced on GoDeploy Labs. They are still looking into the issue.

The labs for Skillable have also changed and you have to create your own environment. Lab 2 says to use Dev One environment, but this does not exist. I had experienced the same problems with GoDeploy on the last course so we switched to Skillable, and this seems to also now have the same problem! This does not have the Expense Report table required for lab 2 - or rather the environment I created does not have it. I will restart the lab and see if it appears.

**Comment by jamarx2** [comment]
I've found that Skillable offers two VMs - one has DevOne predefined and one does not.

**Comment by Derekp20** [comment]
I am using the CloudSlice one. Which one has the Dev One environment?

Derek Pike
________________________________

**Comment by jamarx2** [comment]
The one without the cloud slice has the dev one environment.

**Comment by Derekp20** [comment]
Great thanks. OK, it has Dev. One environment and the Expense Report table, but there is no data. 2 weeks ago it had data as well. But that is much better. than not having it at all!
________________________________

**Comment by CeleneA** [comment]
I will follow up with Skillable to see what the issue is.

**Comment by jamarx2** [comment]
It looks like this has been fixed? Can someone please confirm.

**Comment by CeleneA** [comment]
Yes - it is fixed. It was an issue with the GoDeploy environment.
