### ISSUE TITLE
Create new tables preview feature creates 3 tables with Copilot

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#115]
# Module: 3
#### Step: 5

Description of issue

Instead of creating one table, 3 tables are created. The remainder of the lab instructions are now incorrect

**Comment by julians1966** [comment]
Selecting options and choosing One table may solve the issue

![image](https://github.com/user-attachments/assets/f785f2cd-1915-4729-b5aa-20e037c70125)

**Comment by a-ainamdar** [comment]
Thank you for raising this issue. We will review this and update soon

**Comment by CeleneA** [comment]
Lab steps were updated. Thanks for the tip, Julian!
