### ISSUE TITLE
Get Started with Power Apps error while creating icon

### ISSUE THREAD

**Issue by himanshuahlawat31** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#12]
# Module: 03
#### Step: 04

Description of issue
while adding icon in layout the code provided is not working and throwing error as invalid argument,
![image](https://user-images.githubusercontent.com/57964598/89812071-2f495d00-db5d-11ea-909d-29e11d70bf14.png)

Repro steps:

1.
1.
1.

**Comment by chandlersyal** [comment]
Retested in delta teach with many students and did not encounter this issue. Please reach out if you are still running into it.
