### ISSUE TITLE
"Entity" now referred to as "Table"

### ISSUE THREAD

**Issue by anwoodru** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#23]
# Module: 02
#### Step: 02

"Entity" is now referred to as "Table" effective November 2020 as per https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-solution. Labs require updating to reflect the terminology change.

Repro steps:

1. Attempt to complete Step 2 and 11 and both refer to a table as "Entity".

**Comment by chandlersyal** [comment]
There is a disclaimer for this terminology change. These labs will be updated soon with the new terminology, but we have been waiting on UI updates.
