### ISSUE TITLE
"Field" now referred to as "Column"

### ISSUE THREAD

**Issue by anwoodru** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#24]
# Module: 02
#### Step: 02

Field is no longer selectable by a student going through these labs. It is now referred to as a Column as per this document. https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-solution.

Labs require updating to reflect this. 

Repro steps:

1.
1.
1.

**Comment by chandlersyal** [comment]
There is a disclaimer for this terminology change. These labs will be updated soon with the new terminology, but we have been waiting on UI updates.
