### ISSUE TITLE
Mod 2: Data Modeling, Exercise 2, Task 2 step 2

### ISSUE THREAD

**Issue by AustinP00** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#25]
# Module: 02
##### Step: 02

Description of issue
- No selection for "Entity" in the dropdown menu within the "Solutions" > "'name' Campus Management"

Repro steps:

1. ReAdjust the instructions to follow new set of guidelines that matches the environment to allow continuation within the lab.

![](https://learnondemand.zendesk.com/attachments/token/QOaNXxs5GKKVdGK5LBFBrXSnc/?name=inline744054909.png)

**Comment by chandlersyal** [comment]
Thank you. Please see disclaimer about terminology changes. You should select +New > Table instead of +New > Entity. This will be updated soon in the lab steps.
