### ISSUE TITLE
Environment Language Setting

### ISSUE THREAD

**Issue by TeacherStijn** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#26]
# Module: 00
#### Step: 02

Description of issue
Would advise to set the environment language in this step to English. This will make sure all the standard tables have the correct names. Otherwise f.e. the imports etc. will not work.

Repro steps:

1.
1.
1.

**Comment by chandlersyal** [comment]
Good callout. Thanks!
