### ISSUE TITLE
Tablename Visit or Visits

### ISSUE THREAD

**Issue by TeacherStijn** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#27]
# Module: 02
#### Step: 02

Description of issue
The display name advised to use is 'Visit'. However, during the most of the rest of the course references are made to a 'Visits' table.

Repro steps:

1.
1.
1.

**Comment by chandlersyal** [comment]
This is common to refer to the plural version of a table name. Apologies for the confusion. We will review this usage with the next update this coming week.
