### ISSUE TITLE
Module 2: Timeout or generic errors when creating solution and/or publisher

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#28]
# Module: 02
#### Step: 00

Description of issue

In some cases, you will receive an error (either a timeout, or just a generic error') when attempting to create the <lastname> Campus Management solution, using the 'Bellows College' publisher.  

Repro steps:
 
Follow steps to this exer/task, unfortunately the error is intermittent.  

When it happens, we are not recycling an old tenant, trying to create multiple other solutions simultaneously, and we are following the instructions verbatim as-written from a fresh enviro, using a fresh tenant.  

When it does occur, the downloadable error log file indicates:

![image](https://user-images.githubusercontent.com/49700217/103492065-568b1a00-4ddd-11eb-82e5-071ddcbec42f.png)

One can workaround the issue by cancelling, waiting for some # of minutes, and then re-trying Exercise 1/Task 1 again, until 
 it succeeds.  Having no insight into the backend I can't say for sure this error is actually caused because solutions are being imported, but it does seem as if this is a frequent enough possibility that there should be a warning or other caveat contained within the instructions of the course indicating to try again if one recv's such an error.

 
1.
1.
1.

**Comment by chandlersyal** [comment]
My assumption is that this was a one-off issue. Please reach out if you are continuing to experience, as I am unable to recreate the issue on my end.
