### ISSUE TITLE
Unable to create Production Environment with a Database

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#3]
# Module: 03
#### Step: 04

Description of issue

There is no capacity available on the tenant. It is not possible to create a Production environment; change Production to Trial

Repro steps:

1.
1.
1.

**Comment by alwweb** [comment]
Warning that people can only have 1 trial environment at a time.

**Comment by chandlersyal** [comment]
tenants have changed for this and been validated
