### ISSUE TITLE
Status failure on verify of data input

### ISSUE THREAD

**Issue by ShelleyGiles** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#32]
# Module: 2
#### Step: 3

Description of issue. I am trying to verify my data input, however, the status is failed. 

Repro steps:

1. I have completed all delegated steps in the PL900 instructions lab 
1.
1.
![verify data input](https://user-images.githubusercontent.com/79006090/107848967-eedfda00-6e32-11eb-9ea5-d2fd27c28e84.JPG)

**Comment by ShelleyGiles** [comment]
Please advise on how I can ensure my flow status will be successful. Thank you.

**Comment by PeterKessler** [comment]
Keep an eye on the names of the tables and fields. They must match exactly with the names in the lab description.
