### ISSUE TITLE
'All files' has duplicate files

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#34]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

1. Download Lab Files from GitHub or execute Download Lab Files from Authorized Lab Hoster 
2. Extract the files / watch the files 
3. Sub folder 'Labs' with same files and with the deleted CampusData.zip

**Comment by chandlersyal** [comment]
Can you please provide a screenshot? I will follow up with lab hosters to ensure the deleted CampusData.zip from October is removed.
