### ISSUE TITLE
Power Platform Licence

### ISSUE THREAD

**Issue by guthubcloudittogether** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#39]
# Module: 01 - 06
#### Step: 00

Description of issue
There are some known issues from Lab providers in relation to this course. I am aware of some changes from Microsoft has introduced the developers plan.  Could anyone confirm whether all the labs still work 100% under the suggested trial version which is being suggested in these labs, or have changes been made, as such the guides need to change to the developers plan.
Repro steps:

1.
1.
1.

**Comment by miralon** [comment]
Lab 01 Module 0 prepare environment,  Ex 1-Setup:  when I try to create a trial environment: Currently, Dynamics 365 apps can only be enabled for production environment. You can create trial here

**Comment by chandlersyal** [comment]
The steps laid out in these lab instructions are still the official Microsoft guidance for completing the labs in an instructor led setting. Are you completing this with an Authorized Lab Hoster?
