### ISSUE TITLE
Markdown in GitHub Pages

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#4]
There are formatting issues due to special characters that need to be escaped. Example:

![image](https://user-images.githubusercontent.com/1765732/78702394-83ee7a00-78d6-11ea-83ae-e6a789177b71.png)

**Comment by georged** [comment]
That's odd. There is nothing special in the [source](https://github.com/MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals/blob/master/Instructions/Labs/LAB%5BPL-900%5D_Lab06_Power_BI.md) except the pipe character |
Not sure why it's not showing... Can you give the URL you're using?

**Comment by VitalyMCT** [comment]
That's the issue. Pipes in markdown must be escaped with a \, otherwise they create tables. See https://www.markdownguide.org/extended-syntax/#tables

The URL behind the screenshot above is https://microsoftlearning.github.io/PL-900-Microsoft-Power-Platform-Fundamentals/Instructions/Labs/LAB%5BPL-900%5D_Lab06_Power_BI.html

It may affect other labs too.

**Comment by VitalyMCT** [comment]
@georged , the issue is still there, at least in some instances. 

See the same link provided in the ticket for an example.

**Comment by georged** [comment]
@VitalyMCT source has been corrected. Someone else needs to run a build to produce docs for  https://microsoftlearning.github.io/PL-900-Microsoft-Power-Platform-Fundamentals/. I don't control this process

**Comment by anjenni** [comment]
Hi George! Thanks so much for letting us know – I let Sari (the owner of this course) know so he will check them out and build them. Let me know if it doesn’t get fixed 😊 Thank you so much!
