### ISSUE TITLE
PL-900 Microsoft Power Platform Fundamentals (Needs Updated Instructions)

### ISSUE THREAD

**Issue by joshkioh** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#41]
Module 3: Get started with Power Apps
Lab: How to build a canvas app, Part 1
Task #1: Create Canvas App
Step 1-5

Description of issue: 
Power Apps platform has been updated and update has removed Microsoft Dataverse (Legacy) section. Instructions need to be updated to match power app update.

![Instructions](https://user-images.githubusercontent.com/89803873/131386653-6fa2fbdb-243f-4258-8e8f-3cf18fb2dc67.png)
![Repro 1](https://user-images.githubusercontent.com/89803873/131386671-165fc86c-0324-42ea-ac97-f1aa47ed66c5.jpg)
![Repro 2](https://user-images.githubusercontent.com/89803873/131386690-257f1e8d-6901-4d3e-a8f5-44fe80c36b23.jpg)

**Comment by chandlersyal** [comment]
Thank you! This has been updated.
