### ISSUE TITLE
Inadequate service plan

### ISSUE THREAD

**Issue by NorthBee** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#45]
# Module: 2
#### Step: 3

Description of issue
Getting an error message when attempting to turn on Import Data.  "Flow client error returned with status code "Forbidden" and details "{"error":{"code":"MissingAdequateQuotaPolicy","message":"The user 'f60c490a-83ec-4ff0-a5df-ef5dab183b6a' does not have a service plan adequate for the non-Standard connection."

Am using a M365 Developer Program - Free E5 subscription

**Comment by chandlersyal** [comment]
We recommend using the Community Plan for these labs. The Developer Plan might have restrictions that we are not aware of.
