### ISSUE TITLE
Fixed Layouts Not Present in Portal (Module 3, Lab 4)

### ISSUE THREAD

**Issue by JJGriffin** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#46]
# Module: 3
#### Step: 2

Description of issue

No Fixed Layouts appear to be deployed out for the portal. Instead, the student just sees the following:

![image](https://user-images.githubusercontent.com/24753554/140030081-71ca9c8e-ccdb-4806-9c7a-218788aaf362.png)

From there, the rest of the steps in the exercise cannot be completed. Tried this in two trial environments, and the same issue occurs.

Repro steps:

1. Create a new trial environment and portal app, as indicated in the Module 0 Lab Validation setup steps
2. Complete Task 1 and Step 1 within Task 2
3. Attempt to complete Task 3 in Step 1 and the issue will appear.

**Comment by miralon** [comment]
I was able to complete the lab using Blank Template.
