### ISSUE TITLE
Dynamics 365 tenant - instructions in first lab

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#6]
The first paragraph references a provisioning solution that would've been deployed in February-March time frame. What's the current status of the deployment? 

Quote:

> As of January 23, 2020, WWL is unable to provide students with pre-provisioned Dynamics 365 access, and is working on a solution that should be available in the next 4-6 weeks. As a workaround, we are recommending using Dynamics 365 Trial accounts. Each student will be responsible for requesting these. To help students in getting the Dynamics 365 tenants (including Marketing), M365 tenants will be provided through the Authorized Lab Hosters. This is a short-term solution and we will keep all stakeholders including Learning Partners and MCTs updated as progress is made and advise as a more permanent solution timeline for pre-provisioning Dynamics 365 access for lab use is established. Please work with your Authorized Lab Hoster for provisioning of the M365 Tenants for the students and follow the instructions below to use the M365 tenant to secure a Dynamics 365 trial for your appropriate application.

**Comment by chandlersyal** [comment]
The setup steps have been updated. You will see them in Mod 0 Lab 0.
