### ISSUE TITLE
Couldn't find the name and email section (Lab guide content could not be traced)

### ISSUE THREAD

**Issue by goutamir007** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#67]
# Module: 03
## Lab : 03
###Excercise :02
#### Step: 02

Description of issue: We couldn't find the name textbox to input the values and also the email box to input the email of the user. Even tried using the description box for that and tried saving but no use of it.

![image](https://user-images.githubusercontent.com/92869545/158369845-241eaa45-324e-445c-b8d2-46844756c89a.png)

**Comment by chandlersyal** [comment]
closing, as we have published all new labs. Please reach out for any issues.
