### ISSUE TITLE
PL-900 Module 3 error

### ISSUE THREAD

**Issue by behankat** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#68]
# Module: 3
#### Step: 1 - 7

Description of issue
Code throwing errors?? Firstly is the data source not actually, Visits and not visit?  Secondly is the Actual Start column not considered a dropdown, so shouldn't it be is empty?

 If(!IsBlank(Visit) 
   && Visit.Status = 'Status (Visits)'.Active
   && IsBlank(Visit.'Actual Start'),
       DisplayMode.Edit,
       DisplayMode.Disabled
   )

I am trying to study for my PL-900 exam and can't find any solution to this issue anywhere :-(  Please help! Thank you

**Comment by chandlersyal** [comment]
closing, as we have published all new labs. Please reach out for any issues.
