### ISSUE TITLE
LAB[PL-900]_M03Lab01_Canvas_App.md - incorrect instructions

### ISSUE THREAD

**Issue by richard-b2** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#76]
# Module: 03
#### Step: 06

Description of issue:
Text reads: Select the Connect button in the bottom right corner.

There is no 'connect' button.

**Comment by richard-b2** [comment]
I found the issue. The instructions should start from "create" in the left hand menu. 

Maybe add some detail to the instructions and a couple of screen shots. 

thanks

**Comment by CeleneA** [comment]
I believe that the Connect button is pretty clearly visible once you select a table

**Comment by richard-b2** [comment]
The instructions say "locate and select the visits table you created in the previous lab. But also just notice that this isn't very specific - do you mean expand dataverse in the left menu then select the radio button? Or do you mean click on the table. Either way, I don't see a connect button. 

Selected the radio button: 
![image](https://user-images.githubusercontent.com/108451537/192896587-499c44f8-3e50-4678-9ec4-441dc307221f.png)

Selected the table and a new page opens:
![image](https://user-images.githubusercontent.com/108451537/192896650-a74131e0-3984-49d7-812f-681221aa28ad.png)

**Comment by CeleneA** [comment]
I stepped through it again today and you are correct. I will get this updated as quickly as possible. Thank you.

**Comment by CeleneA** [comment]
You need to select the dataverse connection first. Then you will get a screen to select a table. Choose visits and click the Connect button in the bottom right corner.

![image](https://user-images.githubusercontent.com/50712180/195433179-d5f097b4-24c1-4241-b88b-cbceef0a03ea.png)


![image](https://user-images.githubusercontent.com/50712180/195432859-3465c598-f2a5-414d-8b1d-916fdb7f5665.png)
