### ISSUE TITLE
LAB[PL-900]_M03Lab03_Model_App.md - incorrect/unclear instructions

### ISSUE THREAD

**Issue by richard-b2** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#77]
# Module: 03
## Lab/Demo: 03
Task #1: Create app
Step 9.

Description of issue:
"Using the navigation icons on the left side of the screen, select Navigation." - took me ages to figure out, I recommend a screen shot and/or more clarification since the menu is hidden. 

Similarly, this step towards the end is unclear:
"Change view to Today’s Visits." - there's no indication that I need to click the drop down next to Active Visits. 

cheers,

**Comment by CeleneA** [comment]
Hi there,
we try to avoid adding screenshots to the lab steps as the UI changes frequently, and we invite being out of date.
In terms of step 9 - the Navigation icon is all the way on the left side. Yes, it does need to be unhidden but that is part of learning how to navigate.
![image](https://user-images.githubusercontent.com/50712180/192840373-e0f3bf6f-ac06-4da3-a2d8-1910798e7c99.png)

I have updated the lab steps to incorporate your suggestions.
