### ISSUE TITLE
Looping on Sign up for Trial

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#79]
# Module: 00
#### Step: 6

Description of issue
Browser loops when signing up for a Power Apps trial

This doesn't always happen - sometimes it loops and sometimes it works

Workaround:
Use the Microsoft 365 Admin Center https://admin.microsoft.com 
Billing->Purchase Services
Add a Power Apps Per User trial
Add the Power Apps license to MOD Administrator

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by julians1966** [comment]
AS I said it is not every time. When I train a course of 15 maybe 2 students will experience this

This massively affects the course and ruins the student's experience. I suggest you change the trial setup to what I suggested

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by ephiax20** [comment]
I am also unable to replicate this issue during course testing.

**Comment by CeleneA** [comment]
Julian - we have not been able to repro this issue.
