### ISSUE TITLE
Get Data button doesn't exist

### ISSUE THREAD

**Issue by AMorin8787** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#86]
#### Step: 01

The instructions state to log into the PowerBI webapp and select the Get Data button on the bottom left, however that button isn't there. Workaround has been to use the Upload drop down menu in My Workspaces and selecting "Browse".

![Screenshot 2023-01-22 at 11 42 43 AM](https://user-images.githubusercontent.com/48496971/213931734-e99307b3-9fdb-447a-b3e6-fa53074bf038.png)

**Comment by ephiax20** [comment]
@CeleneA @geschwei please can this fix be merged in?
