### ISSUE TITLE
Student Handbook missing

### ISSUE THREAD

**Issue by abey-abraham** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#88]
Description of issue:
Student Handbook missing

Repro steps:
1.readme.md link [Download Latest Student Handbook and AllFiles Content](https://github.com/MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals/releases/latest) does not link to the Student Handbook / Content.

**Comment by CeleneA** [comment]
I also updated the link in the readme file to point to the [Learning Download Center](https://learningdownloadcenter.microsoft.com/).
