### ISSUE TITLE
PL-900 needs reviewing

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals#95]
### Task: all

Description of issue
The steps to create a table and each column don't line up with the make.powerapps.com portal

At the beginning you are told to click + New table and then + New table - but this isn't an option. You have to choose one of the below options:
![image](https://github.com/MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals/assets/114931569/7fcc42dd-5786-4935-92bc-dd7bc66596b5)

If you choose to create a blank table, you don't get the option to choose "business required" or set the "time zone adjustment"
![image](https://github.com/MicrosoftLearning/PL-900-Microsoft-Power-Platform-Fundamentals/assets/114931569/f16b0687-dc5f-4fc0-b4b7-485302c8b394)

I haven't gone beyond Lab 1 but I would imagine that if these steps don't line up with the portal that there will be further issues down the line as well.

**Comment by ephiax20** [comment]
Reviewed, replicated. Instructions now need to read:

Select **+ New table** then **Set advanced properties**.

**Comment by tylerfarmer1** [comment]
When do the instructions get updated?  I'm teaching PL-900 today, and both GitHub and my Lab Hoster are still showing the older instructions.

**Comment by ephiax20** [comment]
Thank you for your patience, this is quite a large change to the Instructions and I have recently been focused on changes in other courses. I will escalate to the Course Content owner.
